"""
Micro-Investing Engine - Interactive Local Setup

Get started in minutes!
"""

import os
import sys
from pathlib import Path
from textwrap import dedent

def print_header():
    print("\n" + "=" * 70)
    print("  MICRO-INVESTING ENGINE - LOCAL DEPLOYMENT SETUP")
    print("=" * 70)
    print("\nThis setup is for LOCAL HOSTING with full customizability.")
    print("You control where it runs, when it runs, and how it runs.")
    print()
    print("Looking for AWS Lambda (serverless) deployment?")
    print("  Navigate to: ../lambda/")
    print("  Run: cd ../lambda && ./build.sh")
    print("  See: ../lambda/README.md for AWS setup")
    print()
    print("Let's get you set up for local deployment!")
    print()

def check_existing_env():
    """
    Function to check if the .env file exists and has the required API keys.
    """
    env_path = Path('.env')
    if env_path.exists():
        with open(env_path, 'r') as f:
            content = f.read()
            if 'ALPACA_API_KEY' in content and 'your_alpaca' not in content:
                return True
    return False

def setup_env_file():
    """
    Function to guide user through creating .env file with API keys.
    """
    print("\nStep 1: API Keys Setup")
    print("-" * 70)
    
    if check_existing_env():
        print("Found existing .env file with API keys")
        use_existing = input("\nUse existing keys? (y/n): ").lower().strip()
        if use_existing == 'y':
            return True
    
    print("\nYou need Alpaca API keys to get started.")
    print("Get them here: https://app.alpaca.markets/paper/dashboard/overview")
    print()
    
    alpaca_key = input("Alpaca API Key: ").strip()
    alpaca_secret = input("Alpaca Secret Key: ").strip()
    
    if not alpaca_key or not alpaca_secret:
        print("\nBoth Alpaca keys are required!")
        return False
    
    # optional: the card caddie for rewards strategy
    print("\nOptional: The Card Caddie API key (only needed for credit card rewards strategy)")
    print("Get it here: https://www.thecardcaddie.com/profile")
    cardcaddie_key = input("The Card Caddie API Key (press Enter to skip): ").strip()
    
    # optional: email notifications
    print("\nOptional: Email notifications (for alerts)")
    smtp_user = input("Your Gmail address (press Enter to skip): ").strip()
    smtp_password = ""
    if smtp_user:
        smtp_password = input("Gmail App Password (press Enter to skip): ").strip()
    
    # write .env file
    env_content = dedent(f"""\
        # Micro-Investing Engine - Environment Variables
        # Generated by setup.py

        # Alpaca Trading (required)
        ALPACA_API_KEY={alpaca_key}
        ALPACA_SECRET_KEY={alpaca_secret}

        # The Card Caddie API (optional - for credit_card_rewards strategy)
        {f'THECARDCADDIE_API_KEY={cardcaddie_key}' if cardcaddie_key else '# THECARDCADDIE_API_KEY=your_key_here'}

        # Email Notifications (optional)
        {f'SMTP_USER={smtp_user}' if smtp_user else '# SMTP_USER=your@gmail.com'}
        {f'SMTP_PASSWORD={smtp_password}' if smtp_password else '# SMTP_PASSWORD=your_app_password'}
        """)
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\nCreated .env file with your API keys")
    return True

def setup_config():
    """
    Function to guide user through configuring their investment strategies.
    Allows selecting multiple strategies at once.
    """
    print("\nStep 2: Choose Investment Strategies")
    print("-" * 70)
    print("\nYou can enable multiple strategies to run simultaneously!")
    print()
    print("Available Strategies:")
    print("  1. Scheduled Investment (Recommended - Easiest!)")
    print("     Invest a fixed amount at regular intervals")
    print("     No transaction data needed")
    print()
    print("  2. Round Up (Spare change from transactions)")
    print("     Requires transaction CSV file")
    print()
    print("  3. Credit Card Rewards (Advanced)")
    print("     Requires The Card Caddie API + transaction CSV")
    print()
    
    print("Select strategies to enable:")
    print("  - Enter numbers separated by commas (e.g., 1,2)")
    print("  - Or press Enter for default (Scheduled only)")
    
    choice = input("\nYour choice [1]: ").strip() or "1"
    
    # parse choices
    selected = []
    for c in choice.split(','):
        c = c.strip()
        if c in ['1', '2', '3']:
            selected.append(c)
    
    if not selected:
        selected = ['1']
    
    # remove duplicates and sort
    selected = sorted(list(set(selected)))
    
    print("\nSelected strategies:")
    strategy_info = []
    
    if '1' in selected:
        print("  [ENABLED] Scheduled Investment")
        print("    Default: $5 daily into VOO (60%) and QQQ (40%)")
        strategy_info.append({
            'name': 'Scheduled Investment',
            'requires_csv': False,
            'requires_api': False
        })
    
    if '2' in selected:
        print("  [ENABLED] Round Up")
        print("    Uses: data/transactions/transactions.csv")
        strategy_info.append({
            'name': 'Round Up',
            'requires_csv': True,
            'requires_api': False
        })
    
    if '3' in selected:
        print("  [ENABLED] Credit Card Rewards")
        print("    Requires: The Card Caddie API key + transaction CSV")
        strategy_info.append({
            'name': 'Credit Card Rewards',
            'requires_csv': True,
            'requires_api': True
        })
    
    # check requirements
    needs_csv = any(s['requires_csv'] for s in strategy_info)
    needs_api = any(s['requires_api'] for s in strategy_info)
    
    print()
    if needs_csv:
        print("Note: Transaction CSV strategies will use data/transactions/transactions.csv")
        print("      Example data is already provided for testing")
    
    if needs_api:
        cardcaddie_key = os.getenv('THECARDCADDIE_API_KEY')
        if not cardcaddie_key:
            print()
            print("WARNING: Credit Card Rewards strategy requires:")
            print("         1. The Card Caddie API key (add THECARDCADDIE_API_KEY to .env)")
            print("            Get it here: https://www.thecardcaddie.com/profile")
            print("         2. Your credit cards added to your account at:")
            print("            https://www.thecardcaddie.com")
            print("         3. Card names in CSV must match card names in your account")
    
    print()
    print("To customize strategies, amounts, or allocations:")
    print("  Edit config.yml after setup completes")
    
    # create config.yml with selected strategies
    _create_config_file(selected)
    
    return True

def _create_config_file(selected_strategies):
    """
    Create config.yml file with selected strategies enabled.
    
    @PARAMS:
        - selected_strategies -> List of strategy numbers ('1', '2', '3')
    """
    # determine which strategies are enabled
    scheduled_enabled = '1' in selected_strategies
    round_up_enabled = '2' in selected_strategies
    rewards_enabled = '3' in selected_strategies
    
    config_content = dedent(f"""\
        # Micro-Investing Engine Configuration
        # Generated by setup.py
        
        # Investment Strategies
        # You can run multiple strategies simultaneously. Each calculates independently,
        # then all amounts are combined for a single trade execution.
        
        strategies:
          # CREDIT CARD REWARDS STRATEGY (Invest your credit card rewards!)
          # Requires: The Card Caddie API key + transaction CSV
          - name: "rewards"
            type: credit_card_rewards
            enabled: {str(rewards_enabled).lower()}
            csv_file: data/transactions/transactions.csv
            min_daily_investment: 1.00
            max_daily_investment: 100.00
            allocation:
              VOO: 0.60
              QQQ: 0.40
        
          # ROUND UP STRATEGY (Spare change investing - requires transaction CSV)
          - name: "spare_change"
            type: round_up
            enabled: {str(round_up_enabled).lower()}
            csv_file: data/transactions/transactions.csv
            min_daily_investment: 1.00
            max_daily_investment: 50.00
            allocation:
              VOO: 1.00
        
          # SCHEDULED STRATEGY (Simple recurring investments - no transaction data needed)
          - name: "daily_investment"
            type: scheduled
            enabled: {str(scheduled_enabled).lower()}
            amount: 5.00
            interval: daily
            allocation:
              VOO: 0.60
              QQQ: 0.40
        
        # Transaction Data Source (for round_up and credit_card_rewards strategies)
        transactions:
          csv_file: data/transactions/transactions.csv
        
        # Card Caddie API (only needed for credit_card_rewards strategy)
        api:
          base_url: https://www.thecardcaddie.com
          key: ${{THECARDCADDIE_API_KEY}}
        
        # Alpaca Brokerage Configuration
        # PAPER TRADING BY DEFAULT, SET TO FALSE FOR LIVE TRADING WITH REAL MONEY
        alpaca:
          api_key: ${{ALPACA_API_KEY}}
          secret_key: ${{ALPACA_SECRET_KEY}}
          paper: true
        
        # Execution Settings
        execution:
          ledger_file: data/ledger/ledger.csv
          log_level: INFO
        
        # Email Notifications (optional)
        notifications:
          enabled: false
          email_to: your@email.com
          smtp_server: smtp.gmail.com
          smtp_port: 587
          smtp_user: ${{SMTP_USER}}
          smtp_password: ${{SMTP_PASSWORD}}
        """)
    
    with open('config.yml', 'w') as f:
        f.write(config_content)
    
    print()
    print("✓ Created config.yml with selected strategies")

def check_dependencies():
    """
    Function to check if required Python packages are installed.
    """
    print("\nStep 3: Check Dependencies")
    print("-" * 70)
    
    required_packages = [
        ('dotenv', 'python-dotenv'),
        ('yaml', 'PyYAML'),
        ('requests', 'requests')
    ]
    
    missing = []
    for import_name, package_name in required_packages:
        try:
            __import__(import_name)
        except ImportError:
            missing.append(package_name)
    
    if missing:
        print("ERROR: Missing required dependencies!")
        print("\nThe following packages need to be installed:")
        for pkg in missing:
            print(f"  - {pkg}")
        print("\nTo install all required packages:")
        print("  pip install -r requirements.txt")
        print("\nOr install manually:")
        print(f"  pip install {' '.join(missing)}")
        return False
    
    print("SUCCESS: All required dependencies are installed")
    return True

def test_connection():
    """
    Function to test Alpaca API connection using paper trading keys.
    """
    print("\nStep 4: Test Connection")
    print("-" * 70)
    
    try:
        # Add core to path for shared clients
        core_path = Path(__file__).parent.parent.parent / 'core'
        if not core_path.exists():
            print("ERROR: Missing 'core/' directory!")
            print(f"Expected location: {core_path}")
            print("\nThe shared code directory is required for this setup.")
            print("Please ensure the full repository is cloned.")
            return False
        
        sys.path.insert(0, str(core_path))
        
        from clients import AlpacaTrader
        from dotenv import load_dotenv
        
        load_dotenv()
        
        alpaca_key = os.getenv('ALPACA_API_KEY')
        alpaca_secret = os.getenv('ALPACA_SECRET_KEY')
        
        if not alpaca_key or not alpaca_secret:
            print("ERROR: API keys not found in .env")
            return False
        
        print("\nTesting Alpaca connection...")
        trader = AlpacaTrader(alpaca_key, alpaca_secret, paper=True)
        account = trader.get_account()
        
        print("SUCCESS: Connected to Alpaca (Paper Trading)")
        print(f"  Account Status: {account['status']}")
        print(f"  Buying Power: ${float(account['buying_power']):.2f}")
        
        return True
        
    except Exception as e:
        print(f"ERROR: Connection failed: {str(e)}")
        print("\nPlease check your API keys and try again.")
        return False

def run_simulation():
    """
    Function to run a test simulation with the configured settings.
    """
    print("\nStep 5: Run Test Simulation")
    print("-" * 70)
    print("\nRunning test simulation with your configuration...")
    print("(This won't execute any real trades)\n")
    
    try:
        import subprocess
        result = subprocess.run(
            [sys.executable, 'main.py', 'simulate'],
            capture_output=True,
            text=True
        )
        
        print(result.stdout)
        
        if result.returncode == 0:
            print("\nSimulation successful!")
            return True
        else:
            print(f"\nSimulation failed: {result.stderr}")
            return False
            
    except Exception as e:
        print(f"Failed to run simulation: {str(e)}")
        return False

def print_next_steps():
    """
    Function to print next steps after setup is complete.
    """
    print("\n" + "=" * 70)
    print("  LOCAL DEPLOYMENT SETUP COMPLETE!")
    print("=" * 70)
    print("\nNext Steps:")
    print("\n1. Test with simulation:")
    print("   python main.py simulate")
    print("\n2. When ready, execute real trades:")
    print("   python main.py run")
    print("\n3. Set up automation (optional):")
    print("   Automate daily investing with cron:")
    print()
    print("   Step 1: Get your full path (run in this directory)")
    print("     pwd")
    print()
    print("   Step 2: Open crontab editor")
    print("     crontab -e")
    print()
    print("   Step 3: Add one of these lines (replace /your/path/ with result from pwd):")
    print("     # Daily at 1 AM")
    print("     0 1 * * * cd /your/path/deployments/local && python main.py run")
    print()
    print("     # Daily at 9 AM")
    print("     0 9 * * * cd /your/path/deployments/local && python main.py run")
    print()
    print("     # Every Monday at 1 AM")
    print("     0 1 * * 1 cd /your/path/deployments/local && python main.py run")
    print()
    print("   Step 4: Save and exit (Ctrl+X, then Y, then Enter in nano)")
    print()
    print("   Cron guide: See README.md for more examples")
    print("\n4. To customize:")
    print("   - Edit config.yml to change strategies, amounts, or allocation")
    print("   - Edit .env to update API keys")
    print()
    print("Need serverless (Lambda) deployment instead?")
    print("   cd ../lambda")
    print("   ./build.sh")
    print("   See ../lambda/README.md for AWS setup")
    print("\n" + "=" * 70)

if __name__ == "__main__":
    """
    Run the interactive setup wizard for the micro-investing engine.
    """
    print_header()
    
    # step 1: api keys
    if not setup_env_file():
        print("\nSetup failed. Please try again.")
        sys.exit(1)
    
    # step 2: strategies
    if not setup_config():
        print("\nSetup failed. Please try again.")
        sys.exit(1)
    
    # step 3: check dependencies
    if not check_dependencies():
        print("\nSetup failed. Please install required dependencies.")
        sys.exit(1)
    
    # step 4: test connection
    if not test_connection():
        print("\nSetup failed. Please check your API keys.")
        sys.exit(1)
    
    # step 4: run simulation
    run_simulation()
    
    # done!
    print_next_steps()